[Desktop Entry]
Name=Yaru-olive
Type=X-GNOME-Metatheme
Comment=Ubuntu Yaru-olive theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Yaru-olive
MetacityTheme=Yaru
IconTheme=Yaru-olive
CursorTheme=Yaru
CursorSize=24
X-Yaru-Dark=false
X-Yaru-Accent-Name=olive
X-Yaru-Accent-Color=#4B8501
/build/yaru-theme-tPUqwl/yaru-theme-23.10.0/obj-x86_64-linux-gnu/gtk/src/Yaru-olive-olive-accent-color-info.scss:42 DEBUG: Contrast optimized accent is #60aa01
